/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BoardSettings: typeof import('./src/components/BoardSettings.vue')['default']
    GameBoard: typeof import('./src/components/GameBoard.vue')['default']
    IMdiDeleteOutline: typeof import('~icons/mdi/delete-outline')['default']
    IMdiPlusBox: typeof import('~icons/mdi/plus-box')['default']
    IMdiShareVariantOutline: typeof import('~icons/mdi/share-variant-outline')['default']
    IMdiTrashCan: typeof import('~icons/mdi/trash-can')['default']
    IMdiTrashCanOutline: typeof import('~icons/mdi/trash-can-outline')['default']
    OfflineRoomList: typeof import('./src/components/OfflineRoomList.vue')['default']
    OnlineRoomList: typeof import('./src/components/OnlineRoomList.vue')['default']
    RoomElement: typeof import('./src/components/RoomElement.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WordCell: typeof import('./src/components/WordCell.vue')['default']
  }
}
